### ISSUE TITLE
Truncated timestamps

### ISSUE THREAD

**Issue by till-s** [pyepics/pyepics#117]
Thanks for pyepics.

I need timestamps in full nanosecond precision but found that ca.get_timestamp and ca.get_timevars round or truncate to microseconds.

The [attached patch](https://github.com/pyepics/pyepics/files/1696411/pyepics-ts-ns.diff.gz) lets get_timevars() add  'posixseconds' and 'nanoseconds' to the return value (analogous to what OnMonitor() provides to the user callback).

**Comment by newville** [comment]
@till-s   Ah, you are right.  These more accurate times are included in the Monitor Events, but aren't reported with `ca.get_timevars()`.   They should be.  If you're up for, please make a Pull Request.  Otherwise, let us know and we'll add this.

`ca.get_timestamp()` reports "seconds from epoch" as a double.  I think that won't be able to report with an precision better than microseconds.  So, I think that if you need `get_timevars()` or monitored events to get nanoseconds.

**Comment by till-s** [comment]
Thanks - for your quick response. I could create a pull request but IMHO it is simpler to use the 2-line patch I submitted (linked from above comment).

**Comment by newville** [comment]
@till-s OK, we'll change this....

**Comment by newville** [comment]
OK, this is now included in master branch...
