### ISSUE TITLE
skip callbacks

### ISSUE THREAD

**Issue by fabianWhoknows** [pyepics/pyepics#122]
Dear PyEPICS developers

I'm working on a script that monitors some PV managed by a softIOC. I created a epics.PV instance for each variable and attached a callback function to it.

I ran into the following problems:
1) when I start the scripts, the callbacks are executed even if the PVs were not changed.
2) I want to be able to change the value of a PV from within the script without executing the callback function. I tried the following:
- disable the callback (pv.clear_auto_monitor())
- change the value (pv.put())
- enable the callback (pv.reconnect())
Unfortunately, the callback gets executed as soon as I call the reconnect() function.

Can you give me some hints on how to prevent the execution of the callbacks in these situations?

Best,
Fabian

**Comment by newville** [comment]
@fabianWhoknows There are two separate levels of callbacks that might be causing some confusion here:

First, PVs are usually set up to use their own callbacks internally so that they always have the latest value.  `PV.clear_auto_monitor()` will stop this, and `PV.reconnect()` is needed to restart it.

Second, there are also user callbacks -- user-defined code that is called when a PV updates.  When you connect with `PV(pvname , callback=onChange)`, that `onChange` function is the user-level callback.  
And, indeed, this will be called with an initial value as the PV connects.

You can add or remove user-level callbacks anytime after a PV is created, so that the callbacks may only live for part of the process.  A PV can have multiple user-level callbacks.  A common use-case for this is GUI code, where you want a callback to update some widget (or maybe two), but if a corresponding widget goes away, you want that callback to go away too.  

To add and remove callbacks after a PV is created, you can use code like

```python
mypv = PV(pvname)

# add a callback, remember the index
cb_index = mypv.add_callback(onUpdateWidget1)

# remove a callback by index
mypv.remove_callback(cb_index)

# remove all callbacks for a PV
mypv.clear_callbacks()
```

This all happens separately from the internal monitoring.   That is, without user-defined callbacks, the PV will still (unless told not to) be updating internally.  Just to be clear, the internal monitoring is needed for the user-defined callbacks to be triggered.

Note that `PV.add_callback()` has a `run_now` (default `False`) option to force running the callback on adding it. 

I think what you want is to use the `add_callback()` and `remove_callback()` methods, which you can put in any place you want.

**Comment by fabianWhoknows** [comment]
@newville 
Thanks for your response!

I think I'm doing exactly what you are suggesting. A dummy version of my script looks as follows:

```
class PVHandel:
  def __init__(self, PV_name):
    self.PV = epics.PV(PV_name)
    self.PV.add_callback(self.callback)
    
    # this is used to skip the first callback
    self.skip_first = True

  def callback(self, value = None, **kwargs):
    if self.skip_first:
      self.skip_first = False
    else:
      # do something with the value
      pass;

  def reset(self):
    # this functions should set the PV value without executing the callback()
    self.PV.clear_auto_monitor()
    self.PV.value = 0
    self.PV.reconnect()


if name == '__main__':
  myPV = PVHandle('aPVname')

  # do something 
  # ..
  # at some point, reset the PV value
  myPV.reset()

  # ..

```

But now I have the problem that after I'm calling myPV.reset(), the callback gets executed anyway..
I cannot reuse the self.skip_first flag since I cannot assure that the PV is not changed from outside my script while the reset() function gets executed.

I figured out that if I call
`epics.caget('aPVname')`
just before attaching the callback in the __init__ function, the callback gets not executed at all.
I thought that a solution might be to update the cache just before reconnecting the callback, but I'm not sure if this is a good idea and how to do that..

Thank you for your help, I'm really stuck here ):

**Comment by fabianWhoknows** [comment]
@newville 

OK I'm really sorry but I misunderstood your answer and of course you are absolutely right!!
If I remove the callback using
`pv.clear_callbacks()`
then changing the PV value and adding the callback again using
`p.add_callback(self.callback)`
it does __not__ execute it again for the changed value.

Nevertheless it seems that by calling
`epics.caget('aPVname')`
just before initializing the PV instance, I can prevent the initial execution of the callback (for some reason it work only 90% of the times (; )

Thank you again for your support and sorry for my babbling in the former comment..

**Comment by newville** [comment]
@fabianWhoknows  If you're really worried about the callback running the first time (but, out of curiosity, is this really a problem -- the callback will be called occasionally), then you can make sure (well, almost make sure) the PV to be connected before you add the callback:

```python
pv = PVpvname)
val = pv.get()   # should fully connect and return value
pv.add_callback(onChange)
```

This might explain why `epics.caget()` works most of the time -- it will create a PV and should wait for it to connect.

**Comment by fabianWhoknows** [comment]
@newville 
Yes you are right, calling `pv.get()` seems to have the same effect as calling `epics.caget('aPVname')`.
But still it does not prevent 100% of the initial executions of the callbacks.. I think I'll stick to my method using a flag to 'prevent' the initial execution.

Since I my case the EPICS variables control the position of a detector setup, I don't want the detector to move to old positions that might have remained in the variables.. I want the detector to only move to positions that were set **after** I started the control script.

Thank you again for your help! I consider my problem solved and think we can close this issue.
