### ISSUE TITLE
naive use of pyepics may result in IOCs running out of memory

### ISSUE THREAD

**Issue by bfrk** [pyepics/pyepics#134]
We recently had a problem with an IOC (RTEMS, mvme2100) running out of memory due to a python script that used pyepics in a way similar to this simplified example:

```
from epics import PV
import time

def test():
    pv1=PV('LC1HT1R:cplPlng:stMotor')
    mem=PV('IOCS1G:memory')
    a=pv1.get()
    print(i,' ', mem.get())
    time.sleep(0.1)

for i in range(1000):
    test()
```

This is of course not a correct way to use pyepics. Unfortunately, not all users who write such scripts are professional programmers. And even those may not see the mistake here on a casual glance: each execution of the loop body will create a new channel. The new channel consumes resources not only on the machine where the client runs, but also on the IOC itself which in this case has a rather limited amount of memory.

I find it a bit worrying that pyepics invites naive users to write progranms in a style that effectively amounts to a denial-of-service attack on IOCs.

IMO it would be better if pyepics either shared multiple channels to the same PV internally, or else disallowed the above style of programming, and instead forced users to create channels explicitly, thereby making it obvious at which points in the program potentially scarce resources are allocated.

**Comment by bfrk** [comment]
Note that I wrote "inadvertant". This is not about security. I fully agree that a determined attacker can easily flood an EPICS control system much faster using the native CA client library.

This issue is about people naively using pyepics in the way demonstrated above. You claim that what happens under the hood in pyepics is that channels are shared. But fact is that that the above script results in the IOC consuming more and more memory. You can easily test this: create a trivial test.db with one record, start "softIoc -d test.db", create a script like the above that continually calls PV("whatever").get() and monitor the memory consumption of the IOC process.

**Comment by newville** [comment]
@bfrk  Well, the channel IDs *are* reused and each trip through the for loop will *not* create a new channel. 

I don't know where the resource problem comes from.  Do you?   I don't see dramatic changes in memory usage myself.  Using IOC Stats, and making 500 PVs to the same PVname, as with
```
pvs = [epics.PV(pvname) for i in range(500)]
```

I see "CA_CONN_CNT" increase by 1, not 500.  I see MEM_FREE decrease slightly, well below 1 Mb.  Perhaps you are seeing different behaviour? 

It could be that making multiple PVs is registering multiple callbacks for connection and access_right events is using more resources than necessary.   The global cache of channels is needed to keep the callbacks from being garbage collected between the PV being initialized and the actual callback being called (and it needs to stay around in case connection changes).  As a result (and, as far as I know), the CA callbacks need to be held in global state.  But these globally cached callbacks have the downside of preventing the PVs themselves from being garbage collected, and the channels and callbacks defined have to live as long as the process (or threading context) does.   I don't know of a clean way to solve this.  We've tried several different approaches.

This is a large part of why we have `get_pv()` and why `caget()/caput()` uses this (another consideration is speed of connection). 

You are right that this is not about security.  But your subject line says that pyepics encourages DOS, and your message suggests that this is a) due to making too many connections and b) somehow unique or special to pyepics.  Those are each simply untrue.

**Comment by bfrk** [comment]
I am sorry about the perhaps too alarming title. Have changed it to describe the situation more precisely.

The increase of memory consumption on the IOC is steady but rather small (not "dramatic"). Our IOC still ran out of memory after a few days.

I appreciate that you have invested effort to avoid creating duplicate channels. Still, fact is that we cannot observe a similar increase in memory consumption on the IOC if the script is changed to create a single PV object at the top level. That means there is _some_ difference between the behavior of the two programs and that difference is noticeable on the server.

The issue you mentioned with callbacks for connection and access_right events may explain that, if these callbacks are registered per PV, not per underlying (shared) channel. I dimly remember that subscribing for changes to the access rights is indeed handled at the protocol layer, so if the native CA client library translates registering a callback to adding such a subscription then this could explain the behavior. I would say this is a bug in the CA client library then, and not in pyepics. I think I will check this out, perhaps ask on core-talk.

Nevertheless, it would be nice if pyepics would avoid triggering this behavior by registering only a single callback for access_rights per Channel.

**Comment by bfrk** [comment]
This is strange. The CA client library has only ca_replace_access_rights_event(). This suggests that calling this function multiple times for the same channel will actually _replace_ an existing callback registration. And the connection_handler is installed when the channel is created. So I don't understand how mutiple callback registration is even possible with this API.

I have also verified that pyepics issues only one name resolution request to the server. So there is only one channel, just as you said.

So I monitored the traffic with tcpdump. Here is my setup:

```
franksen@tiber: ...src/epics-base/3-14-12-7 > cat test.db 
record(stringout,"TESTEST:testrecord") {
    field(VAL,"text")
    field(PINI,"YES")
}
franksen@tiber: ...src/epics-base/3-14-12-7 > PATH=./bin/linux-x86_64:$PATH softIoc -d test.db
Starting iocInit
############################################################################
## EPICS R3.14.12.7
## EPICS Base built Nov  7 2018
############################################################################
iocRun: All initialization complete
epics> dbl
TESTEST:testrecord
```
In another shell I do

`franksen@tiber: ~ > sudo tcpdump -i lo tcp port 5064`

and in yet another shell I run the test scripts. These are:

```
franksen@tiber: /tmp/pyepics-test > cat test1.py 
from epics import PV

pv = PV('TESTEST:testrecord')

for i in range(10):
    print((i,pv.get()))
franksen@tiber: /tmp/pyepics-test > cat test2.py 
from epics import PV

for i in range(10):
    print((i,PV('TESTEST:testrecord').get()))
```

When I run python3 test1.py, the tcpdump tells me

```
franksen@tiber: ~ > sudo tcpdump -i lo tcp port 5064
[...]
13 packets captured
32 packets received by filter
6 packets dropped by kernel
```

Whereas with test2.py I get

```
franksen@tiber: ~ > sudo tcpdump -i lo tcp port 5064
[...]
36 packets captured
80 packets received by filter
8 packets dropped by kernel
```

When I increase the number of runs from 10 to 1000 in both scripts, the tcpdump for test1.py does not change, while for test2.py I get

```
1239 packets captured
4298 packets received by filter
1818 packets dropped by kernel
```

Could it be that you create a new _subscription_ for every PV object? That would explain the behavior I see on the IOC as well as the output of tcpdump.

**Comment by bfrk** [comment]
Here is another test program that demonstrates increasing memory consumption of the IOC and also how the loop continually slows down:

```
from epics import PV
from os import system
from time import clock

i=0
time=0.0
while True:
    PV('TESTEST:testrecord').get()
    i+=1
    if i%1000 == 0:
      print(i)
      system("ps -e -orss,args | grep softIoc | grep -v grep")
      time = clock() - time
      print(time)
```

This is the output I get with a freshly started softIoc:

```
franksen@tiber: /tmp/pyepics-test > python3 test2.py
1000
 6184 softIoc -d test.db
1.144532
2000
 6448 softIoc -d test.db
1.93712
3000
 6712 softIoc -d test.db
4.12782
4000
 6976 softIoc -d test.db
6.812018999999999
5000
 7240 softIoc -d test.db
11.283328000000001
6000
 7504 softIoc -d test.db
16.112444999999997
7000
 8032 softIoc -d test.db
22.6707
8000
 8296 softIoc -d test.db
29.289601
9000
 8560 softIoc -d test.db
37.61630099999999
10000
 8824 softIoc -d test.db
45.96080900000001
```

**Comment by newville** [comment]
@bfrk   Yeah,  I see two potential problems with the access callbacks.   

First,  `pv.__on_access_rights_event` seems like it needs to take a `**kws` argument, as it can sometimes get a "count" argument.  I'm not entirely sure but would guess this is happening for non-"native" DBR types.  It is easy enough to ignore extra keyword args.

It looks like what we *want* to do is always set exactly 1 Access Callback for a Channel, and then have that callback fan out multiple callbacks to each PV object (or channel, if those get defined).   That would mean running "ca_replace_access_rights_event" exactly once (just after channel creation, and so possibly before connection, I think) but still allow for multiple "access callbacks" for multiple PCs, as would be used in case one really wants one app to have two displays of the same PV that should both "go white" on disconnect.

I don't know that this calling `ca_replace_access_rights_event` for each PV creation (even in on an existing Channel) is causing your observation of multiple PV() calls using too much memory on the server, but maybe it is and it seems better to have one callback per *channel* rather than per "PV".

**Comment by bfrk** [comment]
This has nothing to do with access rights callbacks but rather with the normal event callbacks aka subscriptions i.e. calls to ca_create_subscription().

If the test script is modified to pass `auto_monitor=False` to the PV constructor, IOC memory remains stable:

```
franksen@tiber: /tmp/pyepics-test > python3 test2.py
1000
 5776 softIoc -d test.db
1.131036
2000
 5776 softIoc -d test.db
1.8341120000000002
3000
 5776 softIoc -d test.db
3.9659499999999994
4000
 5776 softIoc -d test.db
6.201790000000001
5000
 5776 softIoc -d test.db
10.518192999999998
6000
 5776 softIoc -d test.db
14.827822000000003
7000
 5776 softIoc -d test.db
21.086123999999998
```

**Comment by newville** [comment]
@bfrk   We could try to change the code so that the CA callbacks for Monitor Events and Access Events (and why not Connection Events too) were really per-Channel and that PVs registered their own callback code for these to the client-side, per-context cache.  That would be a pretty significant change and it will not happen quickly unless someone finds it to be enough of a priority to work on.   A quick test of trying to change the Access Events in this way failed some of the unit tests. I am not 100% sure why that is, but I don't have a simulation IOC set up at the moment to investigate fully, and probably won't for at least a month due to other obligations.   Help would be greatly appreciated. 

Pyepics is communication to the IOC only using the documented CA API. Anything that can be done with pyepics could be done easily in C.  Have you raised a similar issue with a similar C program to epics base?  I think they would tell you that "yes, a bad client program can saturate an IOC and run slowly - don't do that". 

Creating new PVs to the same channel in a loop is not naive usage. That would use `caget()` and `caput()`, which would not show such a problem.   Creating a new PV object to the same address is easily avoidable using `get_pv()`.

So, while it might be possible to change the code to make it less likely to saturate an IOCs resources when repeatedly creating a new PV to the same channel, it might also be reasonable to say "don't do that".

**Comment by bfrk** [comment]
> Anything that can be done with pyepics could be done easily in C. Have you raised a similar issue with a similar C program to epics base?

No. If you are programming in C then you explicitly create a subscription using ca_create_subscription, the documentation of which is pretty clear on this point (https://epics.anl.gov/base/R3-15/6-docs/CAref.html#ca_add_event, emphasis is mine):

> Each call to this function consumes resources in the client library **and potentially a CA server** until one of ca_clear_channel() or ca_clear_subscription() is called.

Whereas in pyepics the subscription is created implicitly. The least you should do is to switch the default for the optional `auto_monitor` argument to the `PV` constructor to `False`. As I have demonstrated this solves the issue in a very simple manner.

Note that issuing `ca_get()` calls is not necessarily less efficient compared to setting up a monitor. This depends on the update rate of the PV: if the PV changes faster than the program needs the values, then `ca_get()` is more efficient, whereas setting up a subscription is more efficient if the PV changes less often than the program requires the value. This is the reason both variants to retriev a value from a PV exist in teh first place. So the choice should be made according to what is known about the update rate of the PV.

Another very simple fix is to wrap the PV constructor with a memoizer:

```
from functools import lru_cache

@lru_cache(maxsize=None)
def PV(pvname, *args, **kwargs):
    return epics.PV(pvname, *args, **kwargs)
```

This means that multiple calls to `PV()` wil return the same result if given the same arguments. This would also make the `PV._PVcache_` obsolete (and perhaps even `epics.ca._cache`).

> Creating new PVs to the same channel in a loop is not naive usage.

Most users of pyepics aren't professional programmers but rather physicists. For them it is not necessarily obvious that `PV("test").get()` creates a "new PV object" and that doing so implicitly creates a subscription which in turn consumes resources on an IOC.

**Comment by newville** [comment]
>> Anything that can be done with pyepics could be done easily in C. Have you raised a similar
>>  issue with a similar C program to epics base?

> No.  If you are programming in C then you explicitly create a subscription using 
> ca_create_subscription, the documentation of which is pretty clear on this point  
> (https://epics.anl.gov/base/R3-15/6-docs/CAref.html#ca_add_event, emphasis is mine):
> Each call to this function consumes resources in the client library and potentially a CA server 
> until one of ca_clear_channel() or ca_clear_subscription() is called.

Well, one *can* create a channel and add a subscription to that channel in every iteration of a loop in C.   Again, anything that can  be done with Pyepics can also be done with C.   In a very real (and deliberate) sense, pyepics uses the C API.  You are saying that C users would not do this.  But they could.


> Whereas in pyepics the subscription is created implicitly. The least you should do is to switch 
> the default for the optional auto_monitor argument to the PV constructor to False. As I have 
> demonstrated this solves the issue in a very simple manner.
>
> Note that issuing ca_get() calls is not necessarily less efficient compared to setting up a monitor.
> This depends on the update rate of the PV: if the PV changes faster than the program needs the
> values, then ca_get() is more efficient, whereas setting up a subscription is more efficient if the PV 
> changes less often than the program requires the value. This is the reason both variants to retriev a > value from a PV exist in teh first place. So the choice should be made according to what is known 
> about the update rate of the PV.

You can set a PV to be not monitored, but it is monitiored by default unless it is a large waveform record.   

My experience must be different from yours for `ca_get`.  I find (and a simple script using the `ca` layer could easily test this) that a truly atomic operation for "ca_get" of "create channel, establish connection, and fetch value" *is* rather slow (very near 30 ms, if memory serves).  Using that approach to get more that a few dozen values multiple times in a program ("read all the settings of the Ion Pump") is really noticeable.  OTOH, keeping connections for Channels that will be re-used, and using asynchronous communication are very useful. 

Not using a monitor is *only* ever more "efficient" if the value is changing more than the user cares to know.  In that case, one can create a PV without monitoring it.  That is deliberately not the default.

But this sense of "efficiency" is not our main concern.   With oython, a little bit of inefficiency at the machine level is tolerable for the convenience and efficiency of the physicist.   Using monitors by default is such a convenience:  Create a bunch of PVs, and when you ask for the values you will get the latest values with very little effort.  

> Another very simple fix is to wrap the PV constructor with a memoizer:
> from functools import lru_cache
> @lru_cache(maxsize=None)
> def PV(pvname, *args, **kwargs):
>     return epics.PV(pvname, *args, **kwargs)
>
> This means that multiple calls to PV() wil return the same result if given the same arguments. 

That might be a fine way to do it, except that it is Python3 only, and we are still supporting Python2.7 (no timeline on dropping that support).  The PV cache doesn't seem to be the problem to me, and it is why we have `get_pv()`.

> This would also make the PV._PVcache_ obsolete (and perhaps even epics.ca._cache).

Using an LRU cache might be able to replace the PV cache.  I think it would not be able to replace the ca._cache, which exists mostly to keep callbacks from being garbage collected away as soon as the defining function exits.  That is, the ca cache is not just a convenient way to avoid unnecessary duplication, but to hold per-threading-context state information.

Still, as earlier, changing the subscriptions to be per-Channel instead of per-PV might help with resource usage. If you'd like to try that, I would encourage you to do so.
  
>> Creating new PVs to the same channel in a loop is not naive usage.
>
> Most users of pyepics aren't professional programmers but rather physicists. 

Indeed, many of the authors of pyepics are physicists. ;). 

> For them it is not necessarily obvious that PV("test").get() creates a "new PV object" and 
> that doing so implicitly creates a subscription which in turn consumes resources on an IOC.

Well, they could read the documentation.

What you seem to think is "common for a naive user" actually looks very uncommon to me.  I know many naive physicist pyepics,  and they mostly use `caget()` (as the docs describe), or create PVs before looping (as shown in examples in the docs) or to use `get_pv()`.   

Then again, any use of CA consumes resources on the IOC.  Of course one can write a client app or sequence program that saturates the IOC.   But computer memory is cheap.  People use Python because human time and memory is far more valuable than computer memory.    US$100 would get you approximately 8 Gb of RAM.  Yes, pyepics is definitely going to help people use those resources to make their jobs easier and faster.   If you want people to not crash an IOC, add more memory or move it to a softIOC on a server with more and cheaper memory and a faster network card.  Or show them how to create a PV *before* repeatedly fetching its value in a loop.

**Comment by newville** [comment]
@bfrk I think you may not be understanding what I am saying.  It seems possible that this misunderstanding is deliberate, and that your goal is to not use pyepics.  If that is your goal, that's OK with me.  Several of us know that ample use of pyepics does make our control system more robust, as well as much easier for novices to use.   We're not offended by people who chose different tools.   OTOH, if your goal is to try to help fix shortcomings in pyepics, there are possibilities for doing that.

Pyepics does not leak memory, but it does *use* memory by making full references and monitors by default.  We also use the TIME DBR variants by default and eagerly fetch the CTRL DBR data -- that uses more memory than is strictly necessary for all situations, but the convenience for the user is important.  In general, Python is not particularly concerned with limiting memory usage.  But that is not at all the same as leaking memory.

Repeatedly allocating resources that are then not used will mean that portions of memory will not be accessible and that could stress the memory on some systems.   That can be done in C or in Python.  The CA library is not particularly helpful in preventing one from doing this.  So, don't do that.   Don't create 1000 references to the same pyepics PV() within a loop only to fetch its value once.   That's not how it is intended to work.  Create one PV and re-use it -- that is how they are intended to be used.   As it turns out, the simplest interface to pyepics (that is, the `caget()` and `caput()` functions) do exactly this. 

So, you could help fix shortcomings in pyepics, or show novices how to use it well.  Or you could encourage novices to program with CA in C or Java, and see how well that works out.
