### ISSUE TITLE
Multiple disconnects result in "CAC: TCP circuit creation failure because "Too many open files"" error and Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by CarlosCumming** [pyepics/pyepics#171]
I am writing a health monitor, therefore this code must be robust and handle misbehaving ioc's. During testing I'm using pcispy to simulate a sioc that repeatedly crashes. The pcispy test script runs for two minutes serving two PV's then exits. A bash script waits a couple of minutes, then restarts it.

My health monitor code monitors the PV's on the pcispy test ioc test fixture. It uses ca.create_channel(pvname, callback = onConnectionChange) to watch for connection changes. Currently, the callback does nothing but report the disconnect (and I cannot find any documented advise on how to handle disconnects).

Currently, it runs fine for the first 1000ish connect/disconnects. Unfortunately, it then gives me the, "Too many open files" error, and Segfaults. Not surprisingly, my ulimit is 1024. I'm running on Ubuntu 18.04 / python3.

It seems that either there is some documentation that I'm not finding or pyepics is not handling disconnects cleanly.

Thank you, tom.c

**Comment by klauer** [comment]
What versions are you running (pyepics, Python, etc.)? Can you post some sample code to reproduce this easily?

We have applications that communicate simultaneously with 10s of thousands of EPICS PVs using pyepics and haven't run into this just yet.

**Comment by CarlosCumming** [comment]
pyepics 3.3.1
Python 2.7.15rc1

I was afraid someone would ask for code :) Follows is a stripped down version.

`
#!/usr/bin/env python3

import os
import time
from epics import ca

os.environ['EPICS_CA_ADDR_LIST'] = "10.2.2.255 10.2.5.43 10.2.126.101 10.2.10.21"
os.environ['EPICS_BASE']         = "/usr/local/epics/"
os.environ['EPICS_HOST_ARCH']    = "linux-x86_64"
os.environ['PYEPICS_LIBCA']      = "/usr/local/epics/lib/linux-x86_64/libca.so"

maxhistory = 1000			# Maximum number of pv values to retain.
pvs = {}				# Pv data

class pvData:
  values        = None			# Fifo of values, [0] is most recent value. Using list for easy math.
  timestamps    = None			# Fifo of timestamps, [0] is most recent value.
  ca            = None			# Channel id from pyepics ca module
  subid         = None			# Subscription id
  disconn  	= 0			# Number of disconnects

with open("/tmp/a", "r") as f:
  pvs = { x.strip():pvData() for x in f.readlines() }

def onConnectionChange(pvname, conn, **kws):
  global pvs

  pv = pvs[pvname]

  if conn:
    pv.disconn += 1
    if not pv.subid:	# Subscribe here as create_subscription waits to long if not connected.
      pv.subid = ca.create_subscription(pv.chid, use_time = True, callback=onValueChange)
    print("%s connected" % pvname)
  else:
    print("%s disconnected" % pvname)

def onValueChange(pvname, value, timestamp, ftype, **kws):
  global pvs, maxhistory

  pv = pvs[pvname]

  pv.values.insert(0, value)
  pv.timestamps.insert(0, timestamp)
  if len(pv.values) >= maxhistory:
    pv.values.pop()
    pv.timestamps.pop()


for pvname in pvs:
  pvs[pvname].values     = []
  pvs[pvname].timestamps = []
  pvs[pvname].subid      = None
  pvs[pvname].chid = ca.create_channel(pvname, callback = onConnectionChange)

while True:
  time.sleep(2)
`

**Comment by newville** [comment]
@CarlosCumming  Hm, sorry for the trouble.   I don't know that I've ever found myself in a situation where I needed to look into what happens with 1000 disconnect/re-connects.   

For the "too many open files" exception, I would guess that a new TCP socket is being opened and not closed per connect/disconnect.   I don't think there is anything in the connection management in pyepics that would cause this by itself.  It could be that this is happening internally in libca, but I would be sort of surprised by that.  

Do you get such an error when you do 1000 disconnect/reconnects and *don't* provide a connection callback but do fully connect to the PVs (maybe even creating a subscription)?

**Comment by klauer** [comment]
Nothing looks terribly off in the example code that I see. I ran it while restarting a large example IOC (ADSim), and at least on OSX the used file count doesn't increase on master or 3.3.1.

Would you mind trying `lsof -p (python_process_id_here)` on your machine, @CarlosCumming, to get a better idea which files/sockets are not being cleaned up?

**Comment by CarlosCumming** [comment]
Here you go (grep'd for IPv4 for berivity). Over time the number of lines with, "UDP *:NNNNN" keep increasing.

`python3 2839 tcumming    3u  IPv4 129481348      0t0      UDP *:36735 
python3 2839 tcumming    4u  IPv4 129481349      0t0      UDP *:56172 
python3 2839 tcumming    5u  IPv4 129479592      0t0      TCP emily.hi.gemini.edu:52050->ngnirscc.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming    6u  IPv4 129491477      0t0      TCP emily.hi.gemini.edu:46652->emily.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming    7u  IPv4 129479588      0t0      TCP emily.hi.gemini.edu:46294->mkogmosdc-ap1.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming    8u  IPv4 129494020      0t0      TCP emily.hi.gemini.edu:32862->mkoepicsgw.hi.gemini.edu:44875 (ESTABLISHED)
python3 2839 tcumming    9u  IPv4 129494021      0t0      TCP emily.hi.gemini.edu:46432->gmos.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   10u  IPv4 129479589      0t0      TCP emily.hi.gemini.edu:40474->scs.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   11u  IPv4 129479590      0t0      TCP emily.hi.gemini.edu:52502->mkoepicsgw.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   12u  IPv4 129479591      0t0      TCP emily.hi.gemini.edu:47630->nifs-cc.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   13u  IPv4 129487607      0t0      TCP emily.hi.gemini.edu:46444->ngnirsoiwfs.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   14u  IPv4 129482225      0t0      UDP *:43550 
python3 2839 tcumming   15u  IPv4 129479593      0t0      TCP emily.hi.gemini.edu:57028->mko-dc-ctrl-niri.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   16u  IPv4 129479594      0t0      TCP emily.hi.gemini.edu:57088->mkogwsioc-lv1.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   17u  IPv4 129479595      0t0      TCP emily.hi.gemini.edu:57994->mkobfosioc-lv1.hi.gemini.edu:38459 (ESTABLISHED)
python3 2839 tcumming   18u  IPv4 129479596      0t0      TCP emily.hi.gemini.edu:57948->altairsfo.hi.gemini.edu:5064 (ESTABLISHED)
python3 2839 tcumming   19u  IPv4 129479597      0t0      TCP emily.hi.gemini.edu:52600->mko-cc-niri.hi.gemini.edu:5064 (ESTABLISHED)
`

**Comment by CarlosCumming** [comment]
Hmm. There's got to be a better way to present long lines in this thing.

**Comment by klauer** [comment]
(@CarlosCumming, I tweaked your comment for you. Just use ``` around the lines in the future to get that nice block)

UDP sockets keep increasing... hmm... What version of epics-base is your shared lib from?

**Comment by CarlosCumming** [comment]
Thanks. It looked pretty ugly, and the, "insert code" makes more sense now.

Here's what it's linking too:

/usr/local/epics/lib/linux-x86_64/libca.so.3.15.3

**Comment by klauer** [comment]
Looking at the epics-base changelog, I don't see anything obvious that would relate to the issue in 3.15.3 and on.

@mdavidsaver - if you have a chance, would you mind weighing in here? See code snippet above: R3.15.3, pyepics mainly calls only `ca_create_channel` and `ca_create_subscription`, and UDP sockets are getting created every time the IOC hosting the PVs restarts...

**Comment by CarlosCumming** [comment]
FYI, same symptoms if I removed the callbacks...

```
#!/usr/bin/env python3

import os
import time
from epics import ca

os.environ['EPICS_CA_ADDR_LIST'] = "10.2.2.255 10.2.5.43 10.2.126.101 10.2.10.21"
os.environ['EPICS_BASE']         = "/usr/local/epics/"
os.environ['EPICS_HOST_ARCH']    = "linux-x86_64"
os.environ['PYEPICS_LIBCA']      = "/usr/local/epics/lib/linux-x86_64/libca.so"

maxhistory = 1000			# Maximum number of pv values to retain.
pvs = {}				# Pv data

class pvData:
  values        = None			# Fifo of values, [0] is most recent value. Using list for easy math.
  timestamps    = None			# Fifo of timestamps, [0] is most recent value.
  ca            = None			# Channel id from pyepics ca module
  subid         = None			# Subscription id
  disconn  	= 0			# Number of disconnects

with open("/tmp/a", "r") as f:
  pvs = { x.strip():pvData() for x in f.readlines() }

for pvname in pvs:
  pvs[pvname].values     = []
  pvs[pvname].timestamps = []
  pvs[pvname].chid  = ca.create_channel(pvname)

while True:
  for pvname in pvs:
    try:
      print("PV:", pvname, ca.get(pvs[pvname].chid))
    except:
      print("Cannot get %s" % pvname)
  time.sleep(2)
```

**Comment by newville** [comment]
@CarlosCumming  @klauer Yeah, I definitely see that the number of open file descriptors (especially UDP) for a process with PVs connected to an IOC does steadily increase for each restart of an IOC.  

While I can believe that pyepics may be doing something wrong, I don't know what that might be.  I can also believe that this problem is not with pyepics but with libca.  Honestly, I don't know if anyone tests what a client does when a server disconnects ~1000 times. 

Perhaps it would be worth asking on Tech-Talk?

**Comment by mdavidsaver** [comment]
> UDP sockets are getting created every time the IOC hosting the PVs restarts

UDP sockets are only created when a CA context is created.

FYI. I've run into this sort of problem several times before with [P4P](github.com/mdavidsaver/p4p) and [pyDevSup](https://github.com/mdavidsaver/pyDevSup).  The basic strategies I have come up with are:

1. https://github.com/mdavidsaver/p4p/blob/master/src/p4p/disect.py to look for trends in changes to python object counts.  This helps to detect missing `Py_DECREF()`.  `disect.py` has some bit rot as my recent usage of a c++ class to handler ref. inc/dec has more or less eliminated this class of error.
2. Maintaining counters in c/c++ code when resources are allocated/freed.  I've actually pushed this down into the [PVA code](https://github.com/epics-base/pvDataCPP/blob/master/src/misc/pv/reftrack.h).

The second idea may be more relevant with pyepics.  You might add two counters of CA contexts and channels.  eg. increment the channel counter when calling `ca_create_channel()` and decrement when `ca_clear_channel()`.

With P4P I've integrated these counters as part of my unit tests.  Each test asserts that there has been no net change in any instance counter.  Fair warning though.  While this has proven effective at catching ref. leaks, it took some time to get working and is quite brittle.

```py
len(os.listdir('/proc/self/fd'))
```

A quick (linux specific) way to check the number of open file descriptors.

**Comment by newville** [comment]
@mdavidsaver 

>> UDP sockets are getting created every time the IOC hosting the PVs restarts

> UDP sockets are only created when a CA context is created.

I should update my report using the latest pyepics master branch and (ahem) the pyepics-supplied versions of libca and libCom (which are actually derived from 3.16.2, as at the time I thought that was "latest" not "abandoned dead-end toward 7").

For sure, Pyepics normally calls `ca_context_create()` exactly once, on initialization.  One can clear the cache and start over, but that is highly unusual and not what is happening here. 

Initializing LIBCA and creating a context does appear to create one UDP socket.

Creating and connecting to one channel appears to create another UDP socket and a TCP socket to the IOC.  Creating a second channel to the same IOC creates appears to create no sockets.
Creating a third channel on a different IOC creates another TCP socket.  That all seems believable to me, but it is 2 UDP sockets, not 1.    We are aggressive in pyepics at keeping channels "rich" with callbacks for connection, monitor events, etc.

Killing and then restarting one of the IOCs causes the "CA.Client.Exception,  Virtual circuit disconnect" message in the client process.   The TCP connection goes away on disconnect and eventually returns on reconnect (though it may not be instantaneous if the IOC has been down for more than 30 seconds -- this all seems normal to me).  

But: I am *NOT* seeing the UDP count go up.   It stays at 2.  That is with Python 3.7 and latest pyepics code.

So: I am now *more* confused, as I believe @CarlosCumming reported using pyepics 3.3.1, which should be the same versions of libca/libCom.  I don't know that any change in the pyepics Python code would have changed this behavior, but maybe?


FWIW, w're not clearing channels on IOC disconnect.  We definitely assume (perhaps even "assert") that libca+libCom handles all the actual networking and connection handling.    Pyepics does have to maintain a persistent, process-level cache of CHIDs and other connection status data so that Python does not garbage-collect these away

**Comment by mdavidsaver** [comment]
> which are actually derived from 3.16.2, as at the time I thought that was "latest" not "abandoned dead-end toward 7

FYI. I package the EPICS 7 libraries as a python "module".  cf. https://pypi.org/project/epicscorelibs/ and https://github.com/mdavidsaver/epicscorelibs

**Comment by klauer** [comment]
> UDP sockets are only created when a CA context is created.

I can't imagine even with the original caching system how multiple contexts could have been created given the example code. I guess if you and @CarlosCumming can't reproduce on the latest release/master, we can consider this closed. (I'd be curious enough to `git bisect` and see how this bug was introduced, if that's the case...)

**Comment by CarlosCumming** [comment]
Above is mentioned using ca_clear_channel().. Is it my misunderstanding that ca_clear_channel() is effectively already done for me when a channel disconnects? Could it be this simple?

**Comment by CarlosCumming** [comment]
Reproduces with python3.7 and pyepics 3.2.5.

Adding ca_clear_channel() causes a segfault.

**Comment by newville** [comment]
@CarlosCumming   No, `ca_clear_channel()` is not done when a channel disconnects.   We want it the channel to automatically reconnect when the channel becomes available. 

Like @klauer, I'd be surprised that anything in pyepics could accidentally cause UDP connections to be retained.  But, again, I don't know that anyone has ever tested 1000 disconnects/reconnects vs the number of open file descriptors for a single process.   

I could be persuaded otherwise, but it sure looks like this was a bug in libca or libCom that got fixed somewhere in the 3.15 series, and that updating these libraries used in pyepics 3.3.0 and later is what really fixed this problem.

**Comment by CarlosCumming** [comment]
IHMO, it's not really the 1000 disconnects/reconnects, the real issue is we have resource leak. Never a good thing.

Also, I tried python3.7, and pyepics 3.3.2, and it still reproduces, both with the callback and non-callback versions.

Right now I think we beat this horse to death. I'm going to implement some horrible workaround, such as to monitor my open file count and clobber myself if it reaches some threshold - then a cronjob will restart me and all will be well. YUCK.

I am not convinced yet that this case s/b closed, even in the likely event that the problems in libca - since we don't know that yet. My sample code's simple enough that even if it's garbage code you guys would have pointed any stupid mistakes on my part - so I don't think it's my code.

I'm not sure how to attempt to reproduce this in libca - or I would give it a go (a simple experiment using camonitor didn't reveal anything obvious). I noted above about keeping python objects alive to prevent garbage collection. I wonder if this is also keeping the UDP socket open. 

Here's versions of what I'm running:

```
cat /usr/local/lib/python3.7/dist-packages/pyepics-3.3.2-py3.7.egg/epics/clibs/linux64/README
These shared libraries were built using

Epics Base 3.16.2 on Centos 6.9 with gcc 4.4.7, glibc 2.12

Readline support was turned off by setting
   COMMANDLINE_LIBRARY =

in
   CONFIG_SITE.Common.linux-x86


The patchelf utility (from Anaconda Python) was used to make the shared
libraries portable with the following commands:

  mv libCom.so libComPYEPICS.so
  patchelf --set-soname libca.so libca.so
  patchelf --set-soname libComPYEPICS.so libComPYEPICS.so
  patchelf --set-rpath '$ORIGIN' libca.so
  patchelf --set-rpath '$ORIGIN' libComPYEPICS.so
  patchelf --replace-needed libCom.so.3.16.2 libComPYEPICS.so libca.so
```

**Comment by newville** [comment]
@CarlosCumming 

> IHMO, it's not really the 1000 disconnects/reconnects, the real issue is we have resource leak. Never a good thing.

Uh, well yeah it is not a good thing!  I think we all agree on that.   It appears to be a resource leak that happens on disconnect/reconnect.  We can tell that because when you get to 1000 disconnect/reconnect the leaked resources hit a system limit.    We just aren't sure what is causing it. 

> Also, I tried python3.7, and pyepics 3.3.2, and it still reproduces, both with the callback and non-callback versions.

Yeah, I just tried again and would like to re-re-update my observations from earlier this morning.  With python 3.7 and pyepics 3.3.3 or github master I **DO* also see that the number of UDP connections increases by one with each disconnect.   Reconnect seems to have no effect, only disconnect.

I still do not know whether this is a pyepics-only problem or not.  Like I said before, we could certainly be doing something incorrectly -- I don't know what that would be -- or it could be that the problem really is somewhere else in libca/libCom. 

I agree that the case is not closed. I think we have evidence of a problem, but not many leads....

**Comment by newville** [comment]
@CarlosCumming @klauer  @mdavidsaver   OK I have more evidence, and I am pretty sureI found the problem:

As I did see earlier today I do *NOT* see UDP connections increase when using
      channels = [epics.ca.create_channel(n, connect=True) for n in pvnames]

but I *DO* see them increase when using 
   channels = [epics.PV(n) for n in pvnames]

The difference is that while both forms use `epics.ca._onConnectionEvent()`, the CA/CHID version does not define a python connection callback while the PV version does have python connection callback. In the master branch, these are run in `_CacheItem.run_connection_callbacks()`.    

So, if I hack it so that this function does not actually call the python callbacks, I can alter the UDP leak.     Surprisingly, the connection code for `PV` is not the culprit.  The relevant code in ca.py is: 

```python
# ca.py, line ~254  in the master branch 
        chid_int = self.chid_int
        for callback in list(self.callbacks):
            if callable(callback):
                poll()
                # print( ' ==> connection callback ', callback, conn)
                callback(pvname=self.pvname, chid=chid_int, conn=self.conn)
```

Again, the problem here is *not* the Python `callback(..)`.  The problem is that `poll()`!   It turns out that we do call `poll()` in  `PV._on_connect()` but *only* when the connection state is True, not when False.  In `ca.py` (now in `CacheItem.run_connection_callbacks()` but previously right in `_onConnectionEvent()` )  `poll()` is called no matter what the connection state is.

It appears that we have learned that  calling `epics.ca.poll()` inside a connection event handler when the connection state has gone from `OP_CONN_UP` to `OP_CONN_DOWN` leaks a UDP connection. 

The good news is that is easy to fix.  In fact, replacing the `poll()` with `time.sleep(0.001)` works without leaking UDP connections.   @klauer -- I recommend making this change as part of #165.  
Perhaps we should replace more calls of `ca.poll()` with `time.sleep()`.

And, just to be clear and somewhat ornery:  This is definitely a bug in libca.  We can now demonstrate that calling `pend_event(1.e-5) ; pend_io(1.0)` inside of a connection handler when the connection status is OP_CONN_DOWN will cause a UDP connection that is not released.  The problem is at the C level, it's just easier to find with python.

@CarlosCumming  would you be willing to find and replace that `poll()` in `ca._onConnectionEvent()` with `time.sleep(0.001)` and see if that fixes the problem for you too?

**Comment by CarlosCumming** [comment]
Well, I'll be damn. That fixed it!

Thanks!

**Comment by mdavidsaver** [comment]
In `ca_client_context::pendEvent()` and and `ca_client_context::pendIO()` I find:

```c++
    // prevent recursion nightmares by disabling calls to
    // pendIO () from within a CA callback.
    if ( epicsThreadPrivateGet ( caClientCallbackThreadId ) ) {
        return ECA_EVDISALLOW;
    }
```

I can't explain the appearance of another UDP socket, but It seems clear that calling these functions from within a callback is not a good idea.  I'm also wonder about the need for `time.sleep()` as well.

**Comment by newville** [comment]
@mdavidsaver 
> I can't explain the appearance of another UDP socket

Someone should probably alert the epics base devels of this error.  Yesterday, you said  "UDP sockets are only created when a CA context is created".  I am pretty sure that must be incorrect.  I always see 2 UDP connections, and a disconnecting channel appears to make one that is not managed very well from libca, probably when coupled with `ca_pend_io()`.  I'd like to think it is related to that irritating and irrepressible `Virtual circuit disconnect` message, and that this would be a good motivation to get rid of that line noise, but that is probably wishful thinking. 

>  but It seems clear that calling these functions from within a callback is not a good idea.

Hm, I don't see docs suggesting that, but then I'm not sure I have ever seen docs on how to write a connection callback. 

For sure, one may want to make CA calls within that connection callback, say to get the count, type, name, access, or to create a subscription.  Using a `ca_pend_*()` within that callback might be necessary, or at least a reasonable assumption - certainly other CA calls are permitted.   We definitely call `ca_pend_event()` and `ca_pend_io()` on connection of a pyepics PV  (and also do get count, type, name, access, and create a subscription).  This does not leak UDP sockets, and appears to not cause any problems.  I would be reluctant to remove these calls. 

>  I also wonder about the need for time.sleep().

It may not be necessary here (in the loop through the list of Python callbacks to run).  Basically, the short time.sleep() is there to allow the interpreter lock to be taken by another thread.  That release would also happen with any call to libca.  For almost all use cases of pyepics, that callback() is going to be `PV._on_connect()` which will definitely do some libca calls.  

If someone passed a list of connection callbacks to `epics.ca.create_channel()` that did not call libca or do explicit i/o and took a long time, that could be a noticeable lag.   So the `time.sleep()` is probably not needed, but it is sort of the closest way to emulate `ca.poll()`.

**Comment by mdavidsaver** [comment]
> irritating and irrepressible `Virtual circuit disconnect` message

You can provide your own callback via `ca_add_exception_event()`.  You probably want to do this as the default may `abort()`.

**Comment by mdavidsaver** [comment]
As follow up on this issue now that I'm back from the collaboration meeting.

> Someone should probably alert the epics base devels of this error.

I believe this is what @klauer intended by poking me ;)  Of course anyone can [open a ticket](https://bugs.launchpad.net/epics-base/) as well.

> I always see 2 UDP connections

The number of UDP sockets created by each content depends on details of host configuration eg. how many NICs, and the contents of EPICS_CA_* environment variables.  My point is that this only happens, in libca, when a CA context is created.  Looking at the code, I don't see any way that a call to `ca_pend_io()` on an __existing__ context can result in a new UDP socket being created.

I can't say where exactly this is happening, but my conclusion is that calling, through the pyepics wrapper code, `ca_pend_io()` from a CA callback (on a CA worker thread) is implicitly creating a new CA context each time.

**Comment by mdavidsaver** [comment]
> Basically, the short time.sleep() is there to allow the interpreter lock to be taken by another thread.

Also:

```
While the interpreter steps through your bytecode it periodically drops the GIL,
without asking permission of the thread whose code it is executing,
so other threads can run:
```

https://opensource.com/article/17/4/grok-gil

This is still essentially true of cpython 3.x, though it has been optimized to only happen if another thread is actually waiting for the GIL.

https://github.com/python/cpython/blob/e225bebc1409bcf68db74a35ed3c31222883bf8f/Python/ceval_gil.h#L11-L50

**Comment by newville** [comment]
@mdavidsaver  yes, the GIL is periodically swapped.  Most I/O functions (and time.sleep) will also release the GIL.   Importantly for pyepics, every call to a function defined with ctypes.CFUNCTYPE also releases the GIL.  All pyepics callbacks are defined this way, so that the GIL will be released every time a connection callback, monitor callback, put callback, get callback, or access callback is called.

Like you say, what happens with a released GIL is that some other thread *may* pick it up.   There have definitely been famous reports of bad performance when the GIL is swapped too often, and the algorithm for switching has been tuned some during the Python 3 devel cycle.  We're not going to worry about that much....

Whether we *need* a sleep between calling (possible but not likely) multiple user-supplied connection callback python functions seems like a small point to me.  We know that it cannot be a `ca.poll()` as that will leak UDP connections.  Running the python connection callback will *probably* release the GIL or be very fast. A small sleep may not be necessary for most situations, but it appears to not be causing any harm.

I do not know for sure,  but I strongly suspect that the UDP leak is actually not specific to python and that if `ca_pend_event() ; ca_pend_io()` was placed in a connection callback in pure C that this would also leak UDP sockets on disconnect.   That is, replacing `epics.ca.poll()` with `time.sleep()` within the connection callback definitely fixed the UDP leak.  I am pretty sure the Python interpreter is not creating a UDP socket with `epics.ca.poll()`. OTOH, we know that libca can and does create UDP sockets.  Maybe the context becomes corrupted when the connection callback is called for a disconnected channel.

**Comment by mdavidsaver** [comment]
cf. https://bugs.launchpad.net/epics-base/+bug/1833108 it looks like a call to `ca_pend_io()` in a disconnect callback will implicitly create a new CA context each time.  Note that eg. `ca_name(chid)`, which never implicitly creates a new context, might be a faster alternative to `sleep(0)`.

**Comment by newville** [comment]
@mdavidsaver thanks for looking into this further.  I think we can have a workaround, but it is possible that someone else is also foolish enough to stick a `ca_pend_io()` in a connection callback.

FWIW,  on the one linux box I tried it on `sleep(0)` and `epics.ca.name(chid)` take about the same amount of time of ~800ns (and `pass` takes about 30ns).   I'm not entirely sure that we're aiming for maximum performance here, and `sleep(0)` seems like it has a clearer intent to me.
