### ISSUE TITLE
pyepics cannot establish connection over VPN on MacOS

### ISSUE THREAD

**Issue by hrubiak** [pyepics/pyepics#211]
Hello,
I have a setup where I can access a set of pv's over AnyConnect VPN on a MacBook. When connected over VPN, caget and caput from bash are able to establish a connection to the pv's. However, pyepics seems to not be able to connect to the pv's. I also have a softIOC running on the MacBook for testing, and pyepics can connect to those pv's. I also have a virtualized Windows 10 the MacBook. Curiously, pyepics within the virtualized Windows 10 environment is indeed able to establish the connection to my PV's. I would appreciate any suggestions.
Thanks,
-Ross

**Comment by newville** [comment]
@hrubiak Hm, it definitely works for me on MacOS (10.15.5) with the AnyConnect VPN (4.7).
I'm not 100% sure but would guess that this problem is really a network setting or EPICS_CA_ADDR_LIST value.  
Maybe check from your python script that the EPICS_* environmental variables are the same as used in the shell?

**Comment by hrubiak** [comment]
@newville You were right. Python wasn't seeing the 'EPICS_CA_ADDR_LIST', which I have defined in .bash_profile. Now that I included it explicitly in the 'evn' in launch.json, pyepics can connect to my pv's. Thanks!
