### ISSUE TITLE
CAC: Unable to connect because "Invalid argument" when using pcaspy with pyepics

### ISSUE THREAD

**Issue by jacquelinegarrahan** [pyepics/pyepics#232]
I am using pyepics (3.5.0) with pcaspy (0.7.3) to read and serve inside a subprocess. 

When running the below minimal example, the process fails to exit and instead hangs with the following messages:

<img width="568" alt="Screen Shot 2022-02-01 at 2 28 34 PM" src="https://user-images.githubusercontent.com/25035114/152062427-cbd1a2c7-41f8-46ae-b431-f35f8aec416c.png">

Due to issues with the libca, I initialize before pcaspy import. Without this initialization, I do not run into the hanging invalid messages.

A minimal example:
```python
import epics 
from multiprocessing import Process
from epics.multiproc import CAProcess

# initialize libca before pcaspy import
if not epics.ca.libca:
    epics.ca.initialize_libca()

from pcaspy import SimpleServer


class MyServer(CAProcess):

    def __init__(self):
        super().__init__()

    def run(self):
        val = epics.caget("SOLN:IN20:121:BACT")

        simple_server = SimpleServer()


if __name__ == "__main__":
    server_process = MyServer()
    server_process.start()
```

What is the main problem and how can I handle this to terminate my program correctly?

**Comment by newville** [comment]
@jacquelinegarrahan  I think you are hitting a "known but maybe not well-advertised" conflict between `pycaspy` and `pyepics` that have been discussed some in (@xiaoqiangwang): https://github.com/pyepics/pyepics/issues/176 and https://github.com/paulscherrerinstitute/pcaspy/issues/64

Basically, both `pycaspy` and `pyepics` need to load the dynamic library for CA (`ca.dll`) into the Python program at runtime.  For Windows, both libraries come with their own copy of `ca.dll`.   The problem is that each process can load exactly one version of any dll file.  If there are 2 different versions, conflicts like the one you see will happen.

My recollection is that `pycaspy` loads this when you do `import pycaspy`, so that it loads its version of `ca.dll` without exception.  Fortunately, `pyepics` does not load `ca.dll` on `import epics`, but only when it actually needs to be used.  This allows you to set an environment variable (`PYEPICS_LIBCA`) pointing to the location of a different version of `ca.dll`.  If you're using `pycaspy`, it must be that one - they give no option.  So I think the workaround to this problem is to do

```
import os
import epics
import pcaspy
os.environ['PYEPICS_LIBCA'] = os.path.dirname(pcaspy.__file__)
```

before doing any real CA work.  

Just to be clear, this is a workaround for a bug in `pycaspy` that was pointed out 2 1/2 years ago that they still have not fixed.

**Comment by xiaoqiangwang** [comment]
In that issue paulscherrerinstitute/pcaspy#64, my conclusion is to link PCASpy to static EPICS libraries. And I did that for conda/pypi packages I distributed here, https://anaconda.org/paulscherrerinstitute/pcaspy.
```
$ conda list | grep -E '(pyepics|pcaspy)'
pcaspy                    0.7.3            py38h04863e7_0    paulscherrerinstitute
pyepics                   3.5.0            py38h578d9bd_1    conda-forge
$ python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from epics import PV
>>> from pcaspy import Driver, SimpleServer
```

**Comment by newville** [comment]
@xiaoqiangwang linking to static EPICS libraries does not solve the problem.  The problem is that *all* CA libraries loaded in an application need to be the same library.   Using dynamic libraries makes that possible, using static libraries makes that all bur impossible.  

Can `pycaspy` be loaded from inside a running IOC?  I sincerely doubt so - the IOC has already loaded ca.dll (or libca.so, etc) before it can load any Python module.  

Pyepics allows the location of the dll to be specified at run time (and after  `import epics`).  There are convenience routines to find the dll that will be loaded.   If `pyepics` used the same approach as `pycaspy`, no script would be able to use the two libraries, and `pyepics` would not be able to be imported into a running IOC.  With the 'load dll late, allow it to be specified at runtime', `pyepics` can be made to work with `pcaspy` or run in an IOC.  

Your code snippet won't reveal any problem until you actually do CA work.   With `pyepics`, `ca.dll` has not been loaded with 
`import epics` or `from epics import PV`.  Loading of `ca.dll` happens the first time a real CA connection is needed.

**Comment by xiaoqiangwang** [comment]
Not true. Static linked libraries become parts of the program.

I did run @jacquelinegarrahan 's script and the CA connection succeeds.

**Comment by xiaoqiangwang** [comment]
It could be that his pcaspy package is installed from condo-forge channel, which is dynamically linked to EPICS libraries.

**Comment by jacquelinegarrahan** [comment]
I can confirm that I was using the conda-forge distribution and the paulscherrerinstitute installation solves my problem.
