### ISSUE TITLE
text encoding fallback 

### ISSUE THREAD

**Issue by xiaoqiangwang** [pyepics/pyepics#242]
It is the same issue as described in #87: epics templates contain latin1(iso-8859-1) characters in the DESC/EGU fields. In our cases they could be "°C" for temperature or "µA" for current. 

The current implemented solution is to let user define *PYTHONIOENCODING* as an environment variable. It has two issues,
* This environment variable has the side effect of changing the default encoding for all stdio and file operations in Python[1].
* A site could have mixed encodings of 'utf-8' and a local specific encoding, e.g. 'latin1' for west europe, 'gb18030' for Chinese, etc. Forcing either one would upset the other.

One way as I see is to use 'utf-8' by default but have a configurable fallback encoding. I implemented this scheme in a test branch[2].
* (+) It is biased towards west European user: the default fallback is "latin1". So no behavior change for the original issue reporter.
* (+) ca get handles bytes with mixed encodings.
* (-) ca put converts strings only to 'utf8' bytes. In case other encoding is needed, the user has to provide the encoded bytes, e.g.
   ```
   ## utf-8 by default
   >>> epics.caput('ao.EGU', '°C')
   1
   >>> epics.caget('ao.EGU$')
   array([194, 176,  67,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   >>> epics.caget('ao.EGU')
   '°C'
   ## latin1 by choice
   >>> epics.caput('ao.EGU$', '°C'.encode('latin1'))
   1
   >>> epics.caget('ao.EGU$')
   array([253,  67,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   >>> epics.caget('ao.EGU')
   '°C'
   ```
In a Chinese environment, the fallback encoding is set to "gb18030".
```
$ export PYEPICS_FALLBACK_ENCODING=gb18030
$ python
>>> import epics
>>> epics.caput('ao.EGU', '摄氏度')
1
>>> epics.caget('ao.EGU')
'摄氏度'
>>> epics.caput('ao.EGU', '摄氏度'.encode('gb18030'))
1
>>> epics.caget('ao.EGU')
'摄氏度'
>>> epics.caget('ao.EGU$')
array([201, 227, 202, 207, 182, 200,   0,   0,   0,   0,   0,   0,   0,
```

How do you think of this approach?

[1] https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING
[2] https://github.com/xiaoqiangwang/pyepics/tree/str_fallback_encoding

**Comment by newville** [comment]
@xiaoqiangwang Thanks. If I understand correctly (and with Unicode, probably not!), the CA library is really just treating all string data as not different from "bytes", so no implied encoding at all. 

I guess having a "PYEPICS_ENCODING" (defaulting to "PYTHONIOENCODING") would make sense.   But that requires the user to select one encoding.

Another possibility might be to use cchardet (https://pypi.org/project/chardet/) to guess the best encoding.  Does that seem like a reasonable approach, or do you prefer to not do that and require an explicit setting?  I have no strong opinion here.   Maybe use cchardet if a byte in a string > 128 and no encoding is set?

**Comment by xiaoqiangwang** [comment]
> ... the CA library is really just treating all string data as not different from "bytes", so no implied encoding at all.

You are correct. caput needs to encode unicode strings to bytes and caget decode bytes to unicode strings.

> I guess having a "PYEPICS_ENCODING" (defaulting to "PYTHONIOENCODING") would make sense. But that requires the user to select one encoding.

I wish to use utf-8 by default (it is kinda standard for programmers), and "PYEPICS_ENCODING" as a fallback. So only if "PYTHONIOENCODING" is not empty and not "utf-8", "PYEPICS_ENCODING" will take "PYTHONIOENCODING". Otherwise it should take something like "latin1"(again my bias). 

> Another possibility might be to use cchardet (https://pypi.org/project/chardet/) to guess the best encoding. Does that seem like a reasonable approach, or do you prefer to not do that and require an explicit setting? I have no strong opinion here. Maybe use cchardet if a byte in a string > 128 and no encoding is set?

I did not know this library. My quick check shows it's fairly inaccurate for non-latin encoding and costs extra time, e.g.
```
In [33]: greeting = '你好'.encode('gb18030')
In [34]: chardet.detect(greeting)
Out[34]: {'encoding': 'TIS-620', 'confidence': 0.3598212120361634, 'language': 'Thai'}
In [35]: %timeit chardet.detect(greeting)
245 µs ± 610 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [46]: chardet.detect(b'\xc0C')
Out[46]: {'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}
In [47]: %timeit chardet.detect(b'\xc0C')
185 µs ± 416 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
I am not in favour of bring another dependencies for something not really working.

**Comment by newville** [comment]
@xiaoqiangwang thanks.

On chardet:  there is a noticeably faster C version ("cchardet") that I've been using for parsing data files from various beamlines around the world where it's mostly trying to guess when some "older" beamline data collection system was using latin-1 and not utf-8.   But, I am completely fine with saying that trying to guess the encoding is too slow and inaccurate for `pyepics`.

I also think that setting a default of 'utf-8' and making it possible to override with an ENV variable is completely reasonable here.   So I think: 
   encoding = 'utf-8'
   if PYTHONIOENCODING exists:  encoding = PYTHONIOENCODING 
   if PYEPICS_ENCODING exists: encoding = PYEPICS_ENCODING 
 
seems good to me.

**Comment by xiaoqiangwang** [comment]
Right, I run the same tests with *cchardet* and it is 30x faster. But the accuracy drops the same for any non-latin encoding family.
```
In [12]: %timeit cchardet.detect(b'\xc0C')
6.68 µs ± 44.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

My main view of this issue is not to have a single encoding, but to have a fallback encoding. In SLS, there are templates designed by German speaking developers, who mostly use "latin1" encoding unknowingly. Also there are English speaking developers (me included), who intentionally write in "utf-8" encoding. Only two encodings to mix. I could not imagine someone in SLS would suddenly write Chinese characters in epics templates. ;). 

In such a mixed environment, one environment variable would not do, because I need to read two PVs with different encodings in the same program. That is why I think a fallback encoding set to the traditional local encoding would help.

**Comment by guidoiaquinti** [comment]
From a pure Pythonic point of view, since Python 3.10, with [PEP 0597](https://www.python.org/dev/peps/pep-0597/), if an encoding is not specified, an EncodingWarning can be raised. To avoid this warning, it's recommended to explicitly specify the encoding.

> I wish to use utf-8 by default (it is kinda standard for programmers), and "PYEPICS_ENCODING" as a fallback. So only if "PYTHONIOENCODING" is not empty and not "utf-8", "PYEPICS_ENCODING" will take "PYTHONIOENCODING". Otherwise it should take something like "latin1"(again my bias).
 
 +1

> I also think that setting a default of 'utf-8' and making it possible to override with an ENV variable is completely reasonable here. So I think:
> encoding = 'utf-8'
> if PYTHONIOENCODING exists: encoding = PYTHONIOENCODING
> if PYEPICS_ENCODING exists: encoding = PYEPICS_ENCODING

+1 to the idea of setting a default of `utf-8` and allowing overrides via env variables.

**Comment by newville** [comment]
@guidoiaquinti  It turns out that Python recommendations are not that helpful here.  The CA library is (understandably!) very attached to "multi-language" and "backward compatibility" and anything else that might go into calling API/ABI/interface "stable".

For holding and sending values of strings, CA uses what we (with a "Python3 in 2024 perspective") would call an outdated definition.  In CA, a string is a C-language char* value -- an array of bytes.  It is also limited to 40 bytes.  There is no encoding information included.

Because it is a network protocol, process A on machine X can hold a "string" and be asked to send (either get or put) it to process B on machine Y.  There is no standard way for the encoding of the string to be communicated -- certainly not with the string, but not even (as far as I am aware) even a standardized field or PV for each IOC to advertise an encoding.  To Python,  CA strings are byte arrays.  We choose to decode them.

We currently do decode with the encoding given (
https://github.com/pyepics/pyepics/blob/8d3044172e519143773a013cce1458bd034a56db/epics/utils.py#L7) by


```python
IOENCODING =  os.environ.get('PYEPICS_ENCODING', os.environ.get('PYTHONIOENCODING', 'utf-8'))
```

I think it is fair to say that this is the best we can do.  But, if working in an environment with mixed encodings on different machines or IOCs, there is no way we can truly solve this. 

Another approach hinted at above is to detect/guess the encoding, now probably best done using `charset_normalizer.from_bytes`, would be to try to guess the best encoding,  as with:

```python
string_value = str(charset_normalizer.from_bytes(byte_value).best())
```

I do that in other situations (when reading data files generated at unknown beamlines), but I would suggest that guessing might not be the best thing to do here.  CA environments are generally more stable than that.

We could have an option for a user to select between: 
   a) always decode with encoding from PYEPICS_ENCODING, PYTHONIOENCODING, then UTF-8
   b) guess as with `str(charset_normalizer.from_bytes(byte_value).best())`
   c) leave data a bytes, so that the user must decode them.

I would say that what we are doing is probably sensible, but adding an option to make that selection would not be too hard to do or support.

**Comment by guidoiaquinti** [comment]
Thank you very much for your detailed explanation, @newville 🙇‍♂️

The challenge here seems analogous to handling datetime information where the timezone is unspecified or not propagated correctly across systems. Achieving uniformity in an environment with mixed encodings on different machines or IOCs is a difficult (or even impossible) task.

> We could have an option for a user to select between:
> a) always decode with encoding from PYEPICS_ENCODING, PYTHONIOENCODING, then UTF-8
> b) guess as with str(charset_normalizer.from_bytes(byte_value).best())
> c) leave data a bytes, so that the user must decode them.

From my experience, option B (guessing the encoding) is generally discouraged. In practice, it's often better to explicitly set the encoding. A hard fail is preferable over the risk of incorrectly guessing the encoding.

Again, thank you for the enlightening discussion on this 🙏

**Comment by newville** [comment]
@guidoiaquinti 

>> We could have an option for a user to select between:
a) always decode with encoding from PYEPICS_ENCODING, PYTHONIOENCODING, then UTF-8
b) guess as with str(charset_normalizer.from_bytes(byte_value).best())
c) leave data a bytes, so that the user must decode them.

> From my experience, option B (guessing the encoding) is generally discouraged. In practice, it's often better to explicitly set the encoding. A hard fail is preferable over the risk of incorrectly guessing the encoding.

I completely disagree.

Option A is currently the only possibility, and would almost certainly remain the default.  B or C could be opt-in choices -- currently, they are not available.  Again, they could be.

The issue is 100% that the person writing the pyepics script cannot know with 100% accuracy what the encoding of a string will be. They can rely on conventions within their network, but once those are violated once (say if someone enters a valid Latin-1-encoded name in a string) then the result in the pyepics client will be wrong.

Should a beamline data collection script raise an exception at 3 AM because someone typed a Latin-1 name in a field somewhere?  Err, no, most definitely not.

**Comment by guidoiaquinti** [comment]
Thank you for the explanation. As mentioned earlier, my understanding of the specific use cases is limited. 

I believed that having a hard fail, which would trigger an alert to indicate a problem, was the better approach. This would enable an operator to investigate and ensure all nodes in the network are in compliance with the network specifications. However, I now understand your perspectives is different and it's better to continue operating.
