### ISSUE TITLE
importlib.resources.files not available on py3.8

### ISSUE THREAD

**Issue by dperl-dls** [pyepics/pyepics#266]
In a downstream library I am getting errors on python 3.8 because `AttributeError: module 'importlib.resources' has no attribute 'files'`, which I believe is due to this change: https://github.com/pyepics/pyepics/commit/919ff8dbbc145ba45232ffabc1ff7e73e33d541d

I think the canonical solution is to use https://pypi.org/project/importlib-resources/ for pythons older than 3.9

**Comment by newville** [comment]
@dperl-dls Hm, sorry for the trouble.  I think maybe our test scripts are not correctly specifying Python versions -- this would probably need investigating, but I will have to put that off for a few days.

With only a few months of Py3.8 support left, we might think about how vital it is to fix this.  Like, we could drop support for   Py3.8 now rather than add conditional dependencies and imports.   I don't have a strong preference.

**Comment by dperl-dls** [comment]
Hi @newville , thanks very much for the speedy response. From my point of view, it would be great to drop support for 3.8. But maybe some people still prefer to support it. This is for https://github.com/bluesky/bluesky, where recently at least @mrakitin still thought it was important - do you have an opinion on this?
