### ISSUE TITLE
No way to disable monitors once enabled 

### ISSUE THREAD

**Issue by protofabrik** [pyepics/pyepics#69]
There is a missing functionality that would allow user to disable monitors on a specific CA channel/PV. In general this rarely needed, but it is very important when dealing with fast sources that generate large arrays (for example cameras and fast digitizers) very often (for us ~7MB large arrays at 10Hz). If the monitors are not disabled when not in use a lot of unnecessary network load as well as sources CPU load are generated. 

A work-around is to disconnect from the channel completely when it is not in use, however that is precisely what spawned  the issue #68 . In addition this work around has a side effects in  terms of generating additional broadcast searches as well larger latency compared to having channels persistently connected...

**Comment by tacaswell** [comment]
We have a helper function in ophyd (the hardware abstraction layer we use at NSLS-II) to handle exactly this https://github.com/NSLS-II/ophyd/blob/master/ophyd/signal.py#L414

**Comment by newville** [comment]
@protofabrik Actually, you can remove a particular callback or remove all callbacks for a PV. 

`PV.add_callback()` returns an index that can be used to remove that particular callback (if you have more than 1 callback on a PV -- this happens in large apps):
```python
p = epics.PV('pvname')
def onchanges(value=None, **kws):
      print("Change: " , value)
icb = p.add_callback(onchanges)

time.sleep(20)

p.remove_callback(icb)
```
Each PV has a `callbacks` attribute that is a dict with integer keys (usually 1,2,3,..)  and function+args values, which can be used to discover the callback indices in use.

You can also remove all callbacks with `p.clear_callbacks()`.

Disconnecting a PV *should* be fine , but as in #68, there is a "should definitely fix" bug in reconnecting a disconnected PV.

**Comment by protofabrik** [comment]
Hi, thanks for quick replies. p.clear_callbacks does work, but the underlying monitor (on the CA level) remains connected, which does not solve the problem with large network load (observed trough `nettop` command). I guess the correct behaviour would be to disconnect the underlying CA monitor when there are no callbacks assigned... 

@tacaswell Aha, I see that in your solution you recreate a PV, which I guess fixes the global state issue. I tried something similar, but I've ended with segmentation fault, most probably since the underlying data from one of the numpy arrays got freed. I'll try poking around some more with your solution in mind. 

Thank you both for very quick replies!

**Comment by newville** [comment]
@protofabrik  Generally speaking every PV has a CA-level event callback (unless explicitly told to not have one with `auto_monitor=False` or for large waveforms -- defaults to a count of 65536, no account for intrinsic data size).   This is used to update the internal value, so that the next `PV.get()` returns the latest value, as fast as possible and without doing a network call (again, unless explicitly asked to do that).    

Any callbacks added by the user for a PV are called by the internal callback.

So it might be that what you really want is `PV(pvname, auto_monitor=False)`, or a way to turn that lower level callback on and off?  That might be doable, but I'd have to look into the details.

**Comment by newville** [comment]
@protofabrik I've added a `PV.clear_auto_monitor()` to turn off automatic monitoring of a PV (by doing `ca.clear_subscription`).  Doing `PV.reconnect()` will then re-enable monitoring.  User-defined callbacks are not touched in this process, so that these to functions can be used to temporarily suspend callbacks.

This is now in 3.2.7rc1, though it needs to be added to the documentation.  Sorry it took a year!
