### ISSUE TITLE
why does autosave uses PV() instead of pv_get()?

### ISSUE THREAD

**Issue by mennodoor** [pyepics/pyepics#88]
Hi,

I am really not sure about this, but wouldn't it be saver to use pv_get() instead of PV() to prevent creating lots and lots of objects when this script is used for a data logging system?

regards
menno

**Comment by newville** [comment]
@mennodoor You are right.  Using PV() instead of get_pv() to create objects inside the `autosave` functions will create a PV object for the same Process Variable name each time the function is called.  The underlying connection will be reused, but it definitely would be better to use `get_pv()`.   A PR is welcome!  

Actually, looking at `autosave.save_restore.py` more closely, it might be worth considering changing this to create an AutoSaver class that parsed a request file once and had a `save()` method.  That might be better for the use case of data logging, as the PV objects could be created and connected once and then saved to the proper format more easily, perhaps controlling the naming of sequences of saved files as well.

But, sadly, I *just* released 3.2.7 yesterday (3.2.6 was more than a year earlier).  There are a few outstanding issues, but I think most of them are in on of the categories of "actually resolved, but not confirmed", or "not resolved but apparently rare, and not a clear solution", or "reminders of work that could be done".  I'll ping these outstanding issues over the next week, but would be glad to hear any other suggestions for improvements.

**Comment by newville** [comment]
now fixed to use `get_pv()` in #98, which also adds an `AutoSaver` class for repeatedly saving save files from a single request file.

**Comment by newville** [comment]
fixed in master, soon to be released in 3.3.0
